### ISSUE TITLE
Toggle System Console broken when launched via manager

### ISSUE THREAD

**Issue by jlampel** [DotBow/Blender-Version-Manager#1]
Hey, thanks so much for this app! So incredibly handy. One thing I've noticed is that launching Blender via the app will not let me toggle the system console in the Window menu, while launching the same build via file explorer or the taskbar will. 

This is using Version Manager 1.3, and Blender 2.8 beta.

**Comment by DotBow** [comment]
Hi! Thanx for report.

It is not really an issue because it runs as a child process for the sake of indication of running version and its number of instances.

I think one of the solution might be adding a toggle to turn kinda Dev mode to disable this feature if no needed. For now I don't know workaround for enabling console and watching Blender at the same time.
